### PR TITLE
Use Flask-Boostrap for hosting Bootstrap CSS and JS

### PR DESCRIPTION
**Pull request by layertwo**
Was reading through the thread on Reddit about this project, and noticed a comment about hosting Bootstrap locally on the server, rather than using a CDN. I've used Flask-Bootstrap in the past and found it useful for quickly building and adhering to Bootstrap in Jinja2 templates. 

Some advantages of using this Flask module is that we can push off Bootstrap updates to someone else. When the module updates, Bootstrap will too. Another reason is the new available blocks for templating. See https://pythonhosted.org/Flask-Bootstrap/basic-usage.html

### CODE REVIEW

**Comment by matt852** [comment]
Changing this to development branch to test out changes first.  If everything is successful, this will be pushed into the Master branch as version 1.2.2

**Comment by matt852** [comment]
This appears to break any jQuery I've added.  Specifically in the base.html file and db/viewhosts.html, I load:

- templates/js/count_active_sessions_js.html
- templates/js/datatables_custom_js.html

However in the developer console, I get the following error for both scripts (in those files):

```
(index):15701 Uncaught ReferenceError: $ is not defined
    at (index):15701
```

The error specifically points to the same line in each script/file:

`$(document).ready(function() {`

**Comment by layertwo** [comment]
@v1tal3, I have an idea of what is going on. The Javascript error above (Uncaught ReferenceError) is due to JQuery not being loaded before the specific script is loaded.

The reason for this is because Flask-Bootstrap follows recommended web app practices by placing the script section at the bottom of the page load. The problem we were running into, is due to the way a few of the templates are importing Javascript. It absolutely does get put in before JQuery, Bootstrap, et al. I'm seeing any template pages which imports anything from app/templates/js will be affected.

The solution I'm going to propose, is those template pages (which are really just Javascript in HTML), are moved to their own Javascript files, and the base template includes those Javascript files if the request.path is the same as where they were previously imported.

I'm working on this right now, and I'll provide a new PR for that once it is completed.

**Comment by matt852** [comment]
Ok great.  Thanks for your help and explanations.

**Pull request merged**
